version: '3.1'

services:
    #scrapyd:
    #    build: ./crawler
    #    networks:
    #        - localhost
    #    ports:
    #        - 6800:6800
    #    command: scrapyd
    #    depends_on:
    #        - elastic

    scrapy:
        build: ./crawler
        networks:
            - localhost
        ports:
            - 6800:6800
        volumes:
            - ./crawler:/house-renting/crawler
            - ./data:/house-renting/data
        depends_on:
            - elastic
        command: scrapy crawl douban

    elastic:
        image: elasticsearch
        networks:
            - localhost
        ports:
            - 9200:9200
        volumes:
            - ./data/elastic:/usr/share/elasticsearch/data

    kibana:
        image: kibana
        networks:
            - localhost
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elastic:9200
        depends_on:
            - elastic

networks:
    localhost:

